# =============================================================================
# Payment Service — Build & Deploy to Production (ECR Version)
# =============================================================================
name: "Backend: Deploy Payment Service"

on:
  push:
    branches: ["main"]
    paths:
      - "web-app/ecommerce-microservices/services/payment-service/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::644981759771:role/GitHubActionRole
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.registry }}
          ECR_REPOSITORY: prod-payment-service
          IMAGE_TAG: v${{ github.run_number }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./web-app/ecommerce-microservices/services/payment-service
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update GitOps Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone https://${{ secrets.GITOPS_TOKEN }}@github.com/3MR-MLops/web-app-gitops.git gitops-repo
          cd gitops-repo
          sed -i 's|image: .*webapp-payment-service.*|image: ${{ steps.login-ecr.registry }}/prod-payment-service|' deployment.yaml
          sed -i '/image: .*prod-payment-service/{n;s/\(tag: \).*/\1"v${{ github.run_number }}"/}' deployment.yaml
          if [ -n "$(git status --porcelain)" ]; then
            git add deployment.yaml
            git commit -m "Update payment-service to ECR v${{ github.run_number }} [skip ci]"
            git push
          fi

      - name: Trigger Update on EC2 via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Name,Values=shop-prod-instance" \
            --comment "Update payment-service to v${{ github.run_number }} from ECR" \
            --parameters 'commands=["cd /home/ubuntu/web-app/web-app/ecommerce-microservices", "docker-compose pull payment-service", "docker-compose up -d payment-service"]' \
            --region us-east-1
